sonar.inclusions=webapp/** 
sonar.sources=webapp
sonar.tests=webapp/test
sonar.test.inclusions=webapp/test/**/*.js 
sonar.javascript.lcov.reportPaths=reports/coverage/lcov.info 
sonar.testExecutionReportPaths=reports/Test-execution.xml
